# Astra.nvim Project Configuration
# Generated for testing

[connection]
host = "example.com"
port = 22
username = "user"
password = null
private_key_path = "~/.ssh/id_rsa"
remote_path = "/home/user/project"
local_path = "/home/ethan/work/rust/astra.nvim"

[sync]
auto_sync = false
sync_on_save = true
sync_interval = 30000

[filters]
exclude_patterns = [
  ".git/",
  "*.tmp",
  "*.log",
  ".DS_Store",
  "target/",
  "build/"
]

include_patterns = []

max_file_size = 10485760