// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by build.rs

use std::borrow::Cow;

pub const VERSION_INFO: &str = r#"
version="0.1.0"
git_commit="167b8c7"
build_time="20270392.2"
full_version="0.1.0+20270392.2.167b8c7"
dirty=true
"#;

pub const VERSION: &str = "0.1.0";
pub const BUILD_TIME: &str = "20270392.2";
pub const GIT_COMMIT: &str = "167b8c7";
pub const FULL_VERSION: &str = "0.1.0+20270392.2.167b8c7";
pub const IS_DIRTY: bool = true;

pub fn get_version_display() -> Cow<'static, str> {
Cow::Borrowed(FULL_VERSION)
}

pub fn is_clean() -> bool {
!IS_DIRTY
}
