---
name: Bug Report
description: Report a bug to help us improve Astra.nvim
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Astra.nvim crashes when..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'astra-core sync ...'
        2. See error
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "I expected Astra.nvim to..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "Instead, Astra.nvim..."
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Please copy and paste any error messages you received.
      render: shell
      placeholder: "Error: ..."

  - type: input
    id: astra-version
    attributes:
      label: Astra.nvim Version
      description: What version of Astra.nvim are you using?
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: input
    id: neovim-version
    attributes:
      label: Neovim Version
      description: What version of Neovim are you using?
      placeholder: "v0.9.0"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your Astra.nvim configuration (remove sensitive information).
      render: shell
      placeholder: |
        {
          "host": "example.com",
          "port": 22,
          ...
        }

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "I also tried..."

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the [contributing guidelines](https://github.com/your-username/astra.nvim/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true