# Astra.nvim Configuration
# This file demonstrates the new language configuration feature

[sftp]
host = "example.com"
port = 22
username = "user"
password = "password"
remote_path = "/remote/path"
local_path = "/local/path"

# Language configuration
# Supported languages: en, zh, ja, ko, es, fr, de, ru
# If not specified, will auto-detect from system environment
language = "zh"

[sync]
auto_sync = true
sync_on_save = true
sync_interval = 30000