[sftp]
host = "8.152.204.236"
port = 22
username = "root"
private_key_path = "~/.ssh/id_rsa"
remote_path = "~/test"
local_path = "~/work/rust/astra.nvim"

[sync]
auto_sync = false
sync_on_save = false
sync_interval = 30000
